[Jamie] Text 컴포넌트 수정
Co-Studo/cos-ui pull request #2
Opened 2022-11-10 11:29 UTC by mina-gwak

close #1 

Text 컴포넌트를 사용하다가 텍스트에 밑줄을 넣거나 대문자로 만드는 등 추가적인 속성이 필요해져서 추가해봤습니다!

**text-decoration**
wavy, dotted 등은 overline이나 underline 등 다른 속성과 조합해서 사용해야하기 때문에 모든 케이스를 다 작성할 수 없을 것 같아 단독으로 사용할 수 있는 line-through, overline, underline만 추가해주었습니다. 추가로 이미 적용된 스타일을 제거하기 위한 none도 넣었습니다.

**text-transform**
capitalize, uppercase, lowercase, inherit을 추가했습니다.

2022-11-10 14:44 UTC, jindonyy requested changes
> wavy, dotted 등은 overline이나 underline 등 다른 속성과 조합해서 사용해야하기 때문에

text-decration도 단축법이라서 그런거니 font를 fontSize, fontWeight 나눠쓴거처럼 textDecorationLine 이런식으로 나눠받으면 어떨까싶어요! ([속성 참고](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration#values))
```js
  textDecorationLine: {
    lineThrough: 'line-through',
    overline: 'overline',
    underline: 'underline',
    none: 'none'
  },
  textDecorationStyle: {
    dotted: 'dotted',
    ...
  }
```

2022-11-10 16:36 UTC, mina-gwak commented
@jindonyy 말씀하신 것처럼 나눠서 받는 방법도 있을 것 같네요! 그런데 점선이나 물결무늬 선을 만들 때와 같이 그 외의 속성이 필요하다고 생각되는 곳이 저희 프로젝트에는 없지 않나 싶어요. 필요한 건 링크 같은 것을 표시할 때 쓰이는 밑줄 정도이니 지금 정도의 옵션으로도 충분하지 않을까요??

2022-11-10 17:42 UTC, jindonyy commented
네넵 안쓰고 있긴한데 overline이랑 line-throgh도 사용하는 곳이 없는 거 같은데 넣어놨길래 얘기해봤습니당!

2022-11-11 04:13 UTC, healtheloper approved these changes
> Text 컴포넌트를 사용하다가 텍스트에 밑줄을 넣거나 대문자로 만드는 등 추가적인 속성이 필요해져서 추가해봤습니다!

어떤 상황인지도 같이 알 수있으면 좋겠다는 생각이 들었습니다! 만약 자주 쓰이는 상황이라면 SX 보다 Text.Bold 처럼 만들어 제공하는 것도 좋을 것 같아요.

2022-11-11 04:13 UTC, healtheloper commented on packages/react/src/styles/fonts.ts
> +    inherit: 'inherit',
좀 헷갈려서 그런데 inherit 속성은 굳이 주지 않아도 default 로 들어가지 않나요?

2022-11-11 05:04 UTC, mina-gwak commented
@jindonyy 아하 넵! 그래도 underline 라인이랑 비슷하게 단독으로 쓸 수 있는 것들이라 같이 넣어도 되지 않을까 싶었었어요. 그럼 그냥 쓰는 옵션만 두는 게 낫다고 생각하시나요??

2022-11-11 05:11 UTC, mina-gwak commented on packages/react/src/styles/fonts.ts
> +    inherit: 'inherit',
> 어떤 상황인지도 같이 알 수있으면 좋겠다는 생각이 들었습니다!

<img width="400" alt="인덱스 페이지" src="https://user-images.githubusercontent.com/62706988/201267501-a68f897e-671a-4417-b9a8-c643200ea6f3.png">

설명이 좀 부족했네요..! playground 인덱스 페이지를 만들면서 링크 밑에 들어가는 밑줄이나 소제목을 대문자로 표시하는 부분에서 필요성을 느꼈던 것 같아요.

> 좀 헷갈려서 그런데 inherit 속성은 굳이 주지 않아도 default 로 들어가지 않나요?

저도 넣을까 말까 하긴 했는데 fonts 내의 다른 속성에 inherit 값이 들어가있는 것들이 있어서 일단 넣어뒀었습니다! 사실 쓸 일은 없을 것 같긴 하네요 😕

2022-11-15 06:11 UTC, hemudi approved these changes
주간회의에서 얘기가 나온대로 딱 필요한 속성들만 잘 남겨주셨네요!! 
수고하셨어요!!
LGTM 입니당! ^0^)b

2022-11-15 06:45 UTC, jindonyy approved these changes
굿굿! 반영 감사합니다!

2022-11-15 07:10 UTC, merged