[Hemdi] Component Story 추가
Co-Studo/cos-ui pull request #52
Opened 2023-03-16 18:14 UTC by hemudi

close #50 

## ✨ 구현 내역
form 을 제외하고 기존 playground-react 패키지에 있던 예시 코드들을 각 컴포넌트들의 경로에 Default 라는 이름으로 옮겼습니다.
또한 props 를 스토리북을 통해 컨트롤 하며 테스트 가능한 컴포넌트들은 추가로 Custom 등의 이름으로 추가해놨습니다!

![스크린샷 2023-03-17 오전 3 13 35](https://user-images.githubusercontent.com/34249911/225714435-c8d736cb-7edb-47fc-89ab-72a67ac540d8.png)

2023-03-17 04:31 UTC, healtheloper requested changes
많은 story 코드를 작성해주셨네요.. 수고많으셨어요 !!
이제 playground 는 보내줘도 될 것 같네요, 간단한 수정사항 같이 리뷰드립니다.

2023-03-17 04:31 UTC, healtheloper commented on packages/primitives/tsconfig.json
> +      "@constants/*": ["constants/*"]
primitives 엔 constants 폴더가 없어서 없어도 되는 경로 같습니다

2023-03-17 04:31 UTC, healtheloper commented on packages/primitives/src/components/IntersectListener/intersectListener.stories.tsx
> +import { FlexBox, Paper, Text } from '@cos-ui/react';
react 패키지가 primitives 를 사용하기에 
primitives 에서도 react 를 사용하면 Circular dependency 가 될 것 같아요.

참고 : https://channel.io/ko/blog/monorepo-in-operation

추가적으로 netlify 빌드 실패한 것도 primitives 에서 react 모듈을 찾지 못해서 그런 것으로 파악되네요, tsc에서 걸려져야하는데 왜 push됐지? 싶어서 branch 받아서 테스트해보고있는데 왜인지 모르게 tsc 동작이 처음 의도대로 동작하지 않아서 저도 이 부분은 찾아보겠습니다.

2023-03-20 05:36 UTC, hemudi commented on packages/primitives/src/components/IntersectListener/intersectListener.stories.tsx
> +import { FlexBox, Paper, Text } from '@cos-ui/react';
모듈 간의 상호참조가 유의해야 할 점인건 당연한건데 미처 고려를 못했네요 ㅠㅂㅠ)>
참고 자료도 첨부해주셔서 감사합니다! 넘나 알찬 글이네요!
금일내로 수정해서 올리겠습니당!! ^0^)b

2023-03-21 13:56 UTC, hemudi commented
## 변경사항
### 1. babel-loader 설치
<img width="875" alt="스크린샷 2023-03-21 오후 10 48 15" src="https://user-images.githubusercontent.com/34249911/226625857-ebad5a2e-a019-4e88-b4c0-fffbf1219014.png">
이전에는 babel-loader 가 없어도 storybook 이 잘 실행이 됐었는데 dev 작업 내역과 합친 뒤 실행을 시켜보니 갑자기 위와 같은 에러가 발생했습니다.


[Cannot find module 'babel-loader/package.json'](https://github.com/storybookjs/storybook/issues/4672)

그래서 우선은 위 글을 참고하여 babel-loader 를 추가하여 해결 했습니다. 명확한 원인은 좀 더 파악을 해봐야 할 것 같습니다.


### 2. intersectListener 스토리 파일에서 @cos-ui/react 제거

### 3. primitives 사용하지 않는 constants 경로 삭제

2023-03-23 09:13 UTC, healtheloper approved these changes

2023-03-23 09:14 UTC, healtheloper commented
Babel loader 는 storybook 이 webpack 에서 처리할 때 사용하는 듯 보이네요 수고하셨습니다!

2023-03-23 09:14 UTC, merged